# Generated by Django 2.1 on 2018-09-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_on_device', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionondevice',
            options={'verbose_name': 'Подключенное оборудование/клиенты', 'verbose_name_plural': 'Подключенное оборудование/клиенты'},
        ),
        migrations.AddField(
            model_name='connectionondevice',
            name='ip_client',
            field=models.TextField(blank=True, help_text='IP/сеть выделенные клиенту. Если несколько - через ";"'),
        ),
        migrations.AddField(
            model_name='connectionondevice',
            name='vlan',
            field=models.CharField(default='Null', help_text='vlan клиента, если есть', max_length=5),
        ),
        migrations.AlterField(
            model_name='connectionondevice',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий'),
        ),
        migrations.AlterField(
            model_name='connectionondevice',
            name='connected',
            field=models.CharField(help_text='Что подключено к порту', max_length=30),
        ),
        migrations.AlterField(
            model_name='connectionondevice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='connectionondevice',
            name='id_dev',
            field=models.ForeignKey(help_text='ID оборудования, к которому подключен клиент/устройство', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_device.Device'),
        ),
        migrations.AlterField(
            model_name='connectionondevice',
            name='port',
            field=models.PositiveSmallIntegerField(help_text='Порт подключения'),
        ),
        migrations.AlterField(
            model_name='connectionondevice',
            name='update',
            field=models.DateTimeField(auto_now=True, help_text='Дата изменения'),
        ),
    ]
