# Generated by Django 2.1 on 2018-09-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_on_device', '0002_auto_20180903_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionondevice',
            name='ip_client',
            field=models.TextField(blank=True, help_text='IP/сеть выделенные клиенту. Если несколько - через ";"', verbose_name='IP клиента'),
        ),
    ]
