# Generated by Django 2.1 on 2018-09-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connection_on_device', '0003_auto_20180904_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionondevice',
            name='id_dev',
            field=models.ForeignKey(help_text='ID оборудования, к которому подключен клиент/устройство', on_delete=django.db.models.deletion.CASCADE, to='models_device.Device'),
        ),
    ]
