# Generated by Django 2.1 on 2018-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_on_device', '0004_auto_20180917_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionondevice',
            name='port',
            field=models.CharField(help_text='Порт подключения', max_length=10),
        ),
    ]
