# Generated by Django 2.1 on 2018-09-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_cities_city_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('up_connect_ip', models.GenericIPAddressField()),
                ('comment', models.TextField(blank=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities.Cities')),
            ],
            options={
                'verbose_name': 'Установленное борудование',
                'verbose_name_plural': 'Установленное борудование',
            },
        ),
        migrations.CreateModel(
            name='ModelDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, verbose_name='Тип устройства.')),
                ('model', models.CharField(help_text='Модель устройства.', max_length=30)),
                ('ports', models.PositiveSmallIntegerField(help_text='Количество портов.')),
                ('template', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Тип и модель оборудования',
                'verbose_name_plural': 'Типы и модели оборудования',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_device.ModelDevices'),
        ),
    ]
