# Generated by Django 2.1 on 2018-09-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_device', '0002_auto_20180903_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Установленное оборудование', 'verbose_name_plural': 'Установленное оборудование'},
        ),
        migrations.AddField(
            model_name='device',
            name='up_connect_port',
            field=models.PositiveSmallIntegerField(default=1, help_text='порт подключения на вышестоящем устройстве', verbose_name='Порт вышестоящего'),
        ),
        migrations.AlterField(
            model_name='device',
            name='city',
            field=models.ForeignKey(help_text='город подключения', on_delete=django.db.models.deletion.PROTECT, to='cities.Cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP нового устройства', unique=True, verbose_name='IP устройства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.ForeignKey(help_text='модель устройства', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models_device.ModelDevices', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='device',
            name='up_connect_ip',
            field=models.GenericIPAddressField(help_text='IP устройства от которого подключено', verbose_name='IP вышестоящего'),
        ),
        migrations.AlterField(
            model_name='modeldevices',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='modeldevices',
            name='model',
            field=models.CharField(help_text='модель устройства', max_length=30, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='modeldevices',
            name='ports',
            field=models.PositiveSmallIntegerField(help_text='количество портов', verbose_name='Портов'),
        ),
        migrations.AlterField(
            model_name='modeldevices',
            name='template',
            field=models.CharField(help_text='имя файла с шаблоном', max_length=50, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='modeldevices',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Тип устройства'),
        ),
    ]
