# Generated by Django 2.1 on 2018-09-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_device', '0003_auto_20180904_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='incoming_port',
            field=models.PositiveSmallIntegerField(default=1, help_text='приходящий порт', verbose_name='Приходящий порт'),
        ),
    ]
