# Generated by Django 2.1 on 2018-09-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_device', '0004_device_incoming_port'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeldevices',
            options={'ordering': ['model'], 'verbose_name': 'Тип и модель оборудования', 'verbose_name_plural': 'Типы и модели оборудования'},
        ),
        migrations.AlterField(
            model_name='device',
            name='comment',
            field=models.TextField(blank=True, help_text='комментарий', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='device',
            name='incoming_port',
            field=models.CharField(default=1, help_text='приходящий порт (если порт радио - 1)', max_length=10, verbose_name='Приходящий порт'),
        ),
        migrations.AlterField(
            model_name='device',
            name='up_connect_port',
            field=models.CharField(default=1, help_text='порт подключения на вышестоящем устройстве', max_length=10, verbose_name='Порт вышестоящего'),
        ),
        migrations.AlterField(
            model_name='modeldevices',
            name='comment',
            field=models.TextField(blank=True, help_text='комментарий', verbose_name='Комментарий'),
        ),
    ]
