# Generated by Django 2.1 on 2018-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_device', '0005_auto_20180914_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='incoming_port',
            field=models.CharField(default=1, help_text='приходящий порт', max_length=10, verbose_name='Приходящий порт'),
        ),
    ]
