# Generated by Django 2.1 on 2018-09-21 07:32

from django.db import migrations, models
import models_device.models


class Migration(migrations.Migration):

    dependencies = [
        ('models_device', '0006_auto_20180917_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='up_connect_ip',
            field=models.GenericIPAddressField(help_text='IP устройства от которого подключено', validators=[models_device.models.validate_up_connect_ip], verbose_name='IP вышестоящего'),
        ),
    ]
