# Generated by Django 2.1 on 2018-09-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Город', max_length=30)),
                ('region', models.IntegerField(choices=[(1, 'Spb'), (2, 'Region2'), (3, 'Region3'), (4, 'Region4'), (5, 'Region5')])),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
    ]
