# Generated by Django 2.1 on 2018-09-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_prefix',
            field=models.CharField(default='Orel', help_text='Префикс в мнемокоде', max_length=10),
            preserve_default=False,
        ),
    ]
