# Generated by Django 2.1 on 2018-10-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_cities_city_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='region',
            field=models.CharField(choices=[('Spb', 'Spb'), ('Region2', 'Region2'), ('Region3', 'Region3'), ('Region4', 'Region4'), ('Region5', 'Region5')], max_length=10),
        ),
    ]
