# Generated by Django 2.1 on 2018-10-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20181006_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='region',
            field=models.CharField(choices=[(1, 'Spb'), (2, 'Region2'), (3, 'Region3'), (4, 'Region4'), (5, 'Region5')], max_length=10),
        ),
    ]
