# Generated by Django 2.1 on 2018-10-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20181006_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='region',
            field=models.IntegerField(choices=[(1, 'Spb'), (2, 'Region2'), (3, 'Region3'), (4, 'Region4'), (5, 'Region5')]),
        ),
    ]
